### ISSUE TITLE
Users assigned to a canceled shuttle cannot be removed

### ISSUE THREAD

**Issue by LucienBrule** [wtg/shuttle-signups#12]
Currently if a user is on a shuttle that gets canceled, they are forever stuck on said shuttle with no exposed way to unsignup themselves.

**Comment by JCBird1012** [comment]
I don't find that to be an issue. Usually, a cancelled shuttle is most likely going to stay that way. It doesn't particularly matter if a user is "stuck" signed up for a cancelled shuttle. It won't matter either way.

**Comment by JCBird1012** [comment]
If it becomes an issue further down the line, we'll reopen this issue and tackle it then.
