### ISSUE TITLE
[bug] package.json's start script missing

### ISSUE THREAD

**Issue by MJGTwo** [wtg/shuttle-signups#41]
I think this is a simple typo. There is a script for npm called "start-all" that is called by Docker. I changed the script's name to "start" and it worked.

The definition of this script is `"start": "concurrently \"mongod --dbpath=data --smallfiles\" \"tsc --project ./web/\" \"tsc --project ./web/ -w\" \"npm run build-css\" \"nodemon app.js\" ",
`
Does this nominclature have meaning, or is this a typo and it was meant to be "start" instead of "start-all"? It's not address in the README.

**Comment by JCBird1012** [comment]
Hey Michael,

Yeah, this does look like a typo right now... Probably one that was purposeful at one point, but as I see it currently it definitely should be changed to ```start``` within the ```package.json```.

We haven't actually gotten to the point where we're using Docker consistently, so it was easy for us to forget about that! Thanks for the help!
I'll be sure to change it ASAP.

**Comment by MJGTwo** [comment]
yeah np. I wanted to change it myself (to make this open-close) but I didn't have privileges. Thanks for handling it!
